// support for .env, .env.development, and .env.production
require("dotenv").config()
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})

module.exports = {
  siteMetadata: {
    siteUrl: "https://gatsbywordpresshomepage.gatsbyjs.io/",
    title: "Gatsby WordPress Homepage Starter",
    author: `Gatsby`,
    description: "A Gatsby Starter for building homepages with WordPress",
  },
  plugins: [
    {
      resolve: "gatsby-source-wordpress",
      options: {
        url: process.env.WPGRAPHQL_URL,
      },
    },
    "gatsby-plugin-sharp",
    "gatsby-plugin-image",
    "gatsby-transformer-sharp",
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-vanilla-extract",
    "gatsby-theme-wordpress-blog",
    {
      resolve: "gatsby-plugin-manifest",
      options: {
        name: "Gatsby Starter WordPress Homepage",
        short_name: "Gatsby",
        start_url: "/",
        // These can be imported once ESM support lands
        background_color: "#ffffff",
        theme_color: "#004ca3",
        icon: "src/favicon.png",
      },
      excludeFieldNames: ['comments', 'blocksJSON', 'previewBlocks', 'previewBlocksJSON'],
      type: {
        Post: {
          limit: 20,
        },
        Comment: {
          limit: 0,
        },
        MediaItem: {
          lazyNodes: false,
        },
        SsbShortcodeBlock: { exclude: true },
        SsbClickToTweetBlock: { exclude: true },
        UgbAccordionBlock: { exclude: true },
        UgbBlockquoteBlock: { exclude: true },
        UgbBlogPostsBlock: { exclude: true },
        UgbButtonBlock: { exclude: true },
        UgbCtaBlock: { exclude: true },
        UgbCardBlock: { exclude: true },
        UgbColumnBlock: { exclude: true },
        UgbColumnsBlock: { exclude: true },
        UgbContainerBlock: { exclude: true },
        UgbCountUpBlock: { exclude: true },
        UgbDividerBlock: { exclude: true },
        UgbExpandBlock: { exclude: true },
        UgbFeatureGridBlock: { exclude: true },
        UgbFeatureBlock: { exclude: true },
        UgbHeaderBlock: { exclude: true },
        UgbHeadingBlock: { exclude: true },
        UgbIconListBlock: { exclude: true },
        UgbIconBlock: { exclude: true },
        UgbNotificationBlock: { exclude: true },
        UgbNumberBoxBlock: { exclude: true },
        UgbPricingBoxBlock: { exclude: true },
        UgbSeparatorBlock: { exclude: true },
        UgbSpacerBlock: { exclude: true },
        UgbTeamMemberBlock: { exclude: true },
        UgbTestimonialBlock: { exclude: true },
        UgbTextBlock: { exclude: true },
        EedeeBlockGutensliderBlock: { exclude: true },
        EedeeBlockGutenslideBlock: { exclude: true },
        UagbPostGridBlock: { exclude: true },
        UagbPostMasonryBlock: { exclude: true },
        UagbPostCarouselBlock: { exclude: true },
        UagbSectionBlock: { exclude: true },
        UagbButtonsBlock: { exclude: true },
        UagbButtonsChildBlock: { exclude: true },
        UagbInfoBoxBlock: { exclude: true },
        UagbTestimonialBlock: { exclude: true },
        UagbTeamBlock: { exclude: true },
        UagbSocialShareBlock: { exclude: true },
        UagbSocialShareChildBlock: { exclude: true },
        UagbGoogleMapBlock: { exclude: true },
        UagbIconListBlock: { exclude: true },
        UagbIconListChildBlock: { exclude: true },
        UagbRestaurantMenuBlock: { exclude: true },
        UagbRestaurantMenuChildBlock: { exclude: true },
        UagbContentTimelineBlock: { exclude: true },
        UagbPostTimelineBlock: { exclude: true },
        UagbCallToActionBlock: { exclude: true },
        UagbColumnBlock: { exclude: true },
        UagbColumnsBlock: { exclude: true },
        UagbBlockquoteBlock: { exclude: true },
        UagbMarketingButtonBlock: { exclude: true },
        UagbTableOfContentsBlock: { exclude: true },
        UagbHowToBlock: { exclude: true },
        UagbFaqChildBlock: { exclude: true },
        UagbInlineNoticeBlock: { exclude: true },
        UagbWpSearchBlock: { exclude: true },
        UagbReviewBlock: { exclude: true },
        UagbTaxonomyListBlock: { exclude: true },
        CoreGalleryBlock: { exclude: true },
        CoreArchivesBlock: { exclude: true },
        CoreAudioBlock: { exclude: true },
        CoreButtonBlock: { exclude: true },
        CoreButtonsBlock: { exclude: true },
        CoreCalendarBlock: { exclude: true },
        CoreCategoriesBlock: { exclude: true },
        CoreCoverBlock: { exclude: true },
        CoreFileBlock: { exclude: true },
        CoreFreeformBlock: { exclude: true },
        CoreMediaTextBlock: { exclude: true },
        CoreLatestCommentsBlock: { exclude: true },
        CoreLatestPostsBlock: { exclude: true },
        CoreMissingBlock: { exclude: true },
        CoreMoreBlock: { exclude: true },
        CorePreformattedBlock: { exclude: true },
        CorePullquoteBlock: { exclude: true },
        CoreRssBlock: { exclude: true },
        CoreSearchBlock: { exclude: true },
        CoreSeparatorBlock: { exclude: true },
        CoreSocialLinksBlock: { exclude: true },
        CoreSocialLinkBlock: { exclude: true },
        CoreSubheadBlock: { exclude: true },
        CoreTagCloudBlock: { exclude: true },
        CoreTextColumnsBlock: { exclude: true },
        CoreVerseBlock: { exclude: true },
        UgbVideoPopupBlockDeprecatedV1Attributes: { exclude: true },
        CoreHeadingBlockDeprecatedV1Attributes: { exclude: true },
        CoreHeadingBlockDeprecatedV2Attributes: { exclude: true },
        CoreHeadingBlockDeprecatedV3Attributes: { exclude: true },
        CoreHeadingBlockDeprecatedV4Attributes: { exclude: true },
        CoreSpacerBlock: { excludeFieldNames: ['attributes'] },
        CoreEmbedBlock: { excludeFieldNames: ['attributes'] },
        CoreHtmlBlock: { excludeFieldNames: ['attributes'] },
        UagbFaqBlock: { excludeFieldNames: ['attributes'] },
        UgbDesignLibraryBlock: { excludeFieldNames: ['attributes'] },
        UgbImageBoxBlock: { excludeFieldNames: ['attributes'] },
        CoreColumnsBlock: { excludeFieldNames: ['attributes'] },
        CoreColumnBlock: { excludeFieldNames: ['attributes'] },
        CoreGroupBlock: { excludeFieldNames: ['attributes'] },
        YoastHowToBlock: { excludeFieldNames: ['attributes'] },
        YoastFaqBlock: { excludeFieldNames: ['attributes'] },
        CoreParagraphBlock: { excludeFieldNames: ['attributes'] },
        CoreTableBlock: { excludeFieldNames: ['attributes'] },
        CoreQuoteBlock: { excludeFieldNames: ['attributes'] },
        CoreEmbedBlock: { excludeFieldNames: ['attributes'] },
        UagbAdvancedHeadingBlock: { excludeFieldNames: ['attributes'] },
        CoreImageBlock: { excludeFieldNames: ['attributes'] },
        CoreListBlock: { excludeFieldNames: ['attributes'] },
        UgbVideoPopupBlockAttributes: { excludeFieldNames: ['anchor', 'blockBackgroundBackgroundColor', 'blockBackgroundBackgroundColor2', 'blockBackgroundBackgroundColorOpacity', 'blockBackgroundBackgroundColorType', 'blockBackgroundBackgroundCustomSize', 'blockBackgroundBackgroundCustomSizeUnit', 'blockBackgroundBackgroundGradientBlendMode', 'blockBackgroundBackgroundGradientDirection', 'blockBackgroundBackgroundGradientLocation1', 'blockBackgroundBackgroundGradientLocation2', 'blockBackgroundBackgroundImageBlendMode', 'blockBackgroundBackgroundMediaId', 'blockBackgroundBackgroundMediaUrl', 'blockBackgroundBackgroundPosition', 'blockBackgroundBackgroundRepeat', 'blockBackgroundBackgroundSize', 'blockBackgroundBackgroundTintStrength', 'blockBackgroundFixedBackground', 'blockBackgroundMobileBackgroundCustomSize', 'blockBackgroundMobileBackgroundCustomSizeUnit', 'blockBackgroundMobileBackgroundMediaId', 'blockBackgroundMobileBackgroundMediaUrl', 'blockBackgroundMobileBackgroundPosition', 'blockBackgroundMobileBackgroundRepeat', 'blockBackgroundMobileBackgroundSize', 'blockBackgroundTabletBackgroundCustomSize', 'blockBackgroundTabletBackgroundCustomSizeUnit', 'blockBackgroundTabletBackgroundMediaId', 'blockBackgroundTabletBackgroundMediaUrl', 'blockBackgroundTabletBackgroundPosition', 'blockBackgroundTabletBackgroundRepeat', 'blockBackgroundTabletBackgroundSize', 'blockDescriptionAlign', 'blockDescriptionBottomMargin', 'blockDescriptionColor', 'blockDescriptionFontFamily', 'blockDescriptionFontSize', 'blockDescriptionFontSizeUnit', 'blockDescriptionFontWeight', 'blockDescriptionHorizontalAlign', 'blockDescriptionLetterSpacing', 'blockDescriptionLineHeight', 'blockDescriptionLineHeightUnit', 'blockDescriptionMobileAlign', 'blockDescriptionMobileBottomMargin', 'blockDescriptionMobileFontSize', 'blockDescriptionMobileFontSizeUnit', 'blockDescriptionMobileLineHeight', 'blockDescriptionMobileLineHeightUnit', 'blockDescriptionMobileWidth', 'blockDescriptionMobileWidthUnit', 'blockDescriptionTabletAlign', 'blockDescriptionTabletBottomMargin', 'blockDescriptionTabletFontSize', 'blockDescriptionTabletFontSizeUnit', 'blockDescriptionTabletLineHeight', 'blockDescriptionTabletLineHeightUnit', 'blockDescriptionTabletWidth', 'blockDescriptionTabletWidthUnit', 'blockDescriptionTextTransform', 'blockDescriptionWidth', 'blockDescriptionWidthUnit', 'blockHeight', 'blockHeightUnit', 'blockHorizontalAlign', 'blockInnerWidth', 'blockOpacity', 'blockTag', 'blockTitle', 'blockTitleAlign', 'blockTitleBottomMargin', 'blockTitleColor', 'blockTitleFontFamily', 'blockTitleFontSize', 'blockTitleFontSizeUnit', 'blockTitleFontWeight', 'blockTitleHorizontalAlign', 'blockTitleLetterSpacing', 'blockTitleLineHeight', 'blockTitleLineHeightUnit', 'blockTitleMobileAlign', 'blockTitleMobileBottomMargin', 'blockTitleMobileFontSize', 'blockTitleMobileFontSizeUnit', 'blockTitleMobileLineHeight', 'blockTitleMobileLineHeightUnit', 'blockTitleMobileWidth', 'blockTitleMobileWidthUnit', 'blockTitleTabletAlign', 'blockTitleTabletBottomMargin', 'blockTitleTabletFontSize', 'blockTitleTabletFontSizeUnit', 'blockTitleTabletLineHeight', 'blockTitleTabletLineHeightUnit', 'blockTitleTabletWidth', 'blockTitleTabletWidthUnit', 'blockTitleTag', 'blockTitleTextTransform', 'blockTitleWidth', 'blockTitleWidthUnit', 'blockVerticalAlign', 'blockWidth', 'blockWidthUnit', 'blockZIndex', 'borderRadius', 'bottomSeparatorBringToFront', 'bottomSeparatorColor', 'bottomSeparatorDesign', 'bottomSeparatorFlipHorizontally', 'bottomSeparatorFlipVertically', 'bottomSeparatorHeight', 'bottomSeparatorLayer2BlendMode', 'bottomSeparatorLayer2Color', 'bottomSeparatorLayer2FlipHorizontally', 'bottomSeparatorLayer2Height', 'bottomSeparatorLayer2Opacity', 'bottomSeparatorLayer2Width', 'bottomSeparatorLayer3BlendMode', 'bottomSeparatorLayer3Color', 'bottomSeparatorLayer3FlipHorizontally', 'bottomSeparatorLayer3Height', 'bottomSeparatorLayer3Opacity', 'bottomSeparatorLayer3Width', 'bottomSeparatorMobileHeight', 'bottomSeparatorShadow', 'bottomSeparatorTabletHeight', 'bottomSeparatorWidth', 'columnBorderColor', 'columnBorderType', 'columnBorderWidthBottom', 'columnBorderWidthLeft', 'columnBorderWidthRight', 'columnBorderWidthTop', 'columnMobileBorderWidthBottom', 'columnMobileBorderWidthLeft', 'columnMobileBorderWidthRight', 'columnMobileBorderWidthTop', 'columnTabletBorderWidthBottom', 'columnTabletBorderWidthLeft', 'columnTabletBorderWidthRight', 'columnTabletBorderWidthTop', 'customCSS', 'customCSSCompiled', 'customCSSUniqueID', 'height', 'hideDesktop', 'hideMobile', 'hideTablet', 'hoverEffect', 'marginBottom', 'marginLeft', 'marginRight', 'marginTop', 'marginUnit', 'mobileBlockHeight', 'mobileBlockHeightUnit', 'mobileBlockHorizontalAlign', 'mobileBlockOpacity', 'mobileBlockVerticalAlign', 'mobileBlockWidth', 'mobileBlockWidthUnit', 'mobileBlockZIndex', 'mobileHeight', 'mobileMarginBottom', 'mobileMarginLeft', 'mobileMarginRight', 'mobileMarginTop', 'mobileMarginUnit', 'mobilePaddingBottom', 'mobilePaddingLeft', 'mobilePaddingRight', 'mobilePaddingTop', 'mobilePaddingUnit', 'mobileWidth', 'noPaddings', 'paddingBottom', 'paddingLeft', 'paddingRight', 'paddingTop', 'paddingUnit', 'playButtonColor', 'playButtonOpacity', 'playButtonSize', 'playButtonType', 'previewBackgroundColor', 'previewBackgroundColor2', 'previewBackgroundColorOpacity', 'previewBackgroundColorType', 'previewBackgroundCustomSize', 'previewBackgroundCustomSizeUnit', 'previewBackgroundGradientBlendMode', 'previewBackgroundGradientDirection', 'previewBackgroundGradientLocation1', 'previewBackgroundGradientLocation2', 'previewBackgroundImageBlendMode', 'previewBackgroundMediaId', 'previewBackgroundPosition', 'previewBackgroundRepeat', 'previewBackgroundSize', 'previewBackgroundTintStrength', 'previewFixedBackground', 'previewMobileBackgroundCustomSize', 'previewMobileBackgroundCustomSizeUnit', 'previewMobileBackgroundMediaId', 'previewMobileBackgroundMediaUrl', 'previewMobileBackgroundPosition', 'previewMobileBackgroundRepeat', 'previewMobileBackgroundSize', 'previewTabletBackgroundCustomSize', 'previewTabletBackgroundCustomSizeUnit', 'previewTabletBackgroundMediaId', 'previewTabletBackgroundMediaUrl', 'previewTabletBackgroundPosition', 'previewTabletBackgroundRepeat', 'previewTabletBackgroundSize', 'shadow', 'showBlockBackground', 'showBlockDescription', 'showBlockTitle', 'showBottomSeparator', 'showBottomSeparatorLayer2', 'showBottomSeparatorLayer3', 'showTopSeparator', 'showTopSeparatorLayer2', 'showTopSeparatorLayer3', 'tabletBlockHeight', 'tabletBlockHeightUnit', 'tabletBlockHorizontalAlign', 'tabletBlockOpacity', 'tabletBlockVerticalAlign', 'tabletBlockWidth', 'tabletBlockWidthUnit', 'tabletBlockZIndex', 'tabletHeight', 'tabletMarginBottom', 'tabletMarginLeft', 'tabletMarginRight', 'tabletMarginTop', 'tabletMarginUnit', 'tabletPaddingBottom', 'tabletPaddingLeft', 'tabletPaddingRight', 'tabletPaddingTop', 'tabletPaddingUnit', 'tabletWidth', 'topSeparatorBringToFront', 'topSeparatorColor', 'topSeparatorDesign', 'topSeparatorFlipHorizontally', 'topSeparatorFlipVertically', 'topSeparatorHeight', 'topSeparatorLayer2BlendMode', 'topSeparatorLayer2Color', 'topSeparatorLayer2FlipHorizontally', 'topSeparatorLayer2Height', 'topSeparatorLayer2Opacity', 'topSeparatorLayer2Width', 'topSeparatorLayer3BlendMode', 'topSeparatorLayer3Color', 'topSeparatorLayer3FlipHorizontally', 'topSeparatorLayer3Height', 'topSeparatorLayer3Opacity', 'topSeparatorLayer3Width', 'topSeparatorMobileHeight', 'topSeparatorShadow', 'topSeparatorTabletHeight', 'topSeparatorWidth', 'uniqueClass', 'width'] }
      },
    },
  ],
}
